//
// Created by chino on 24/5/2026.
//

#ifndef PROYECTO_2___PROGRA_2_SISTEMANOTIFICACIONES_H
#define PROYECTO_2___PROGRA_2_SISTEMANOTIFICACIONES_H


class SistemaNotificaciones {
};


#endif //PROYECTO_2___PROGRA_2_SISTEMANOTIFICACIONES_H